package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	ADD_FRIEND_REQUEST, ADD_FRIEND_REPLY, TOKEN, REQUEST_TOKEN,
	ADD_FILE, REMOVE_FILE, VIEW_FILE, QUIT_NODE, GOODBYE, REMOVE_UPDATE, BACKUP, PING, IS_ALIVE, ALIVE, PONG, BUDDY, CONFIRMATION,
	TELL_ADD_FILE, TELL_REMOVE_FILE, TELL_ADD_FRIEND, TELL_VIEW_FILE, TELL_QUIT_NODE, TELL_GOODBYE, TELL_WELCOME

}
